### ISSUE TITLE
ZeroSSL issuance support

### ISSUE THREAD

**Issue by fu-sen** [domcloud/dom-portal#3]
DOM Cloud supports Let's Encrypt issuance, so you can often use it without worrying about SSL (TLS).
This what many web services already do.

Therefore, I thought that there was a demand for support to issue ZeroSSL instead of Let's Encrypt;
https://zerossl.com/

I've never seen support for ZeroSSL at the server level. What if it was DOM Cloud ...?

**Comment by willnode** [comment]
DOM Cloud relies on Webmin for issuing SSL. And they only support Let's Encrypt as of now.

You can still use the Webmin panel to install other SSL manually, though I know this is not something you want.

Implementing another SSL issuer may be tricky, and ZeroSSL hides most of their useful features behind a paywall, so probably it's not an ideal solution in near time.

**Comment by fu-sen** [comment]
ZeroSSL is only one year old. The environment for publishing is not yet in place. I may have been too quick to suggest this. 😆

As far as I refer to Webmin, DOM Cloud puts the certificate in the user directory. In addition, DOM Cloud makes it easy to execute arbitrary commands with ssh or templates. You should now be able to issue ZeroSSL. You can also set cron with Webmin, so you can update it. I may be able to explore this concrete means and publish it later.

**Comment by willnode** [comment]
I read their ACME documentation, and yeah as far as I can tell, it can be implemented using just script deployment. I do actually wish they can do anonymous like how Let's Encrypt already does.

Maybe I can craft the deployment template but I got little time to do the research right now. I'll leave this open in case anyone interest.

**Comment by fu-sen** [comment]
I know web server Caddy can issue ZeroSSL. . 
https://caddyserver.com/

I feel the possibility of using Caddy instead of nginx or using nginx as a reverse proxy to refer to Caddy.

**Comment by fu-sen** [comment]
I got ZeroSSL! :
![スクリーンショット 2021-04-06 13 35 54](https://user-images.githubusercontent.com/5434159/113665484-8271b080-96e8-11eb-8ff7-694038b41b26.jpg)

- Many clients require root, but acme.sh allows you to publish as user. And we plan to make ZeroSSL issuance the default in the future:
https://github.com/acmesh-official/acme.sh
- Then log in to Webmin. Specify the issued ZeroSSL and set cron to update automatically.
- If you use templates, you need to remove `features: ssl`. Because it encourages the issuance and automatic update of Let's Encrypt.

I might have a page with a little more detail, but for now I think someone can do this with just this information.

**Comment by fu-sen** [comment]
You seem to have trouble moving the issue. I created New discussions instead and described this detail.
https://github.com/domcloud/domcloud-io/discussions/6

I find it even more convenient to have ZeroSSL supported at the server level, but it's a good situation for this issue and I can close it.
