### ISSUE TITLE
Add Discussions to any GitHub project

### ISSUE THREAD

**Issue by fu-sen** [domcloud/dom-portal#4]
I feel that DOM Cloud has the potential for interesting uses that we can't imagine and that other hosting and web services can't.
Also, this Issues is originally a place to report bugs, but I was already issuing a New Issue because it wasn't.

So I think it's good to add GitHub Discussions in a project somewhere in the DOM Cloud Organization:
https://github.com/github/feedback/discussions

Active projects on GitHub Discussions:
https://github.com/vercel/vercel/discussions

Vercel is probably your rival in some areas, but DOM Cloud still has something that Vercel can't do!

It will be useful not only for interaction between you and users in the future, but also for interaction between users when the number of users increases.
It's a quiet place at first, but users who later discover it will make it more active.

**Comment by willnode** [comment]
I have mentioned in the [readme](https://github.com/domcloud/domcloud-io#readme) that discussions should go here:

[domcloud/domcloud-io/discussions](https://github.com/domcloud/domcloud-io/discussions)

I open to new improvements to the portal so that's why issues and PR still open here.

**Comment by fu-sen** [comment]
Quick and good job! 👍

If you want, you can move Issues to Discussions. It could transfer all my issues.

**Comment by willnode** [comment]
I have transferred your #3 to main repo domcloud/domcloud-io#1 to get more attention.

It seems clear now. Thanks again for your suggestion.
